
development:
  adapter: postgresql
  encoding: unicode
  database: sellfood_development
  pool: 5
  username: postgres
  password: master

test:
  adapter: postgresql
  encoding: unicode
  database: sellfood_test
  pool: 5
  username: postgres
  password: master

production:
  adapter: postgresql
  encoding: unicode
  database: sellfood_production
  pool: 5
  username: postgres
  password: master